# Generated by Django 6.0.1 on 2026-01-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('root_domain', 'Root Domain'), ('subdomain', 'Subdomain'), ('url', 'URL')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cves',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='DNSSecurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('zone_transfer', 'Zone Transfer'), ('dnssec', 'DNSSEC'), ('hijacking', 'DNS Hijacking'), ('subdomain_takeover', 'Subdomain Takeover')], max_length=50)),
                ('finding', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('cvss_score', models.FloatField()),
                ('risk_rating', models.CharField(max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dns_security_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_domain', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['root_domain'],
            },
        ),
        migrations.CreateModel(
            name='EmailSecurityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('SPF', 'SPF'), ('DKIM', 'DKIM'), ('DMARC', 'DMARC')], max_length=20)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('INVALID', 'Invalid')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('cvss_score', models.FloatField()),
                ('risk_rating', models.CharField(max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('record_value', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_security_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('CVE', 'CVE'), ('SSL', 'SSL'), ('DNS', 'DNS'), ('Email', 'Email'), ('Misconfiguration', 'Misconfiguration')], max_length=50)),
                ('nuclei_template_id', models.CharField(max_length=200)),
                ('nuclei_severity', models.CharField(max_length=50)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=200, null=True)),
                ('risk_rating', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('scoring_confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('evidence', models.TextField()),
                ('recommendation', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-cvss_score', '-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='FindingCVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('related', 'Related')], max_length=20)),
            ],
            options={
                'db_table': 'finding_cves',
            },
        ),
        migrations.CreateModel(
            name='FrontendLibraryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
                ('detected_version', models.CharField(max_length=100)),
                ('latest_version', models.CharField(max_length=100)),
                ('vulnerability_status', models.CharField(choices=[('up-to-date', 'Up-to-date'), ('outdated', 'Outdated'), ('vulnerable', 'Vulnerable')], max_length=20)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('source_urls', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'frontend_library_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.IntegerField(blank=True, null=True)),
                ('scan_type', models.CharField(choices=[('on-demand', 'On-Demand'), ('scheduled', 'Scheduled'), ('triggered', 'Triggered')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_started', models.DateTimeField(blank=True, null=True)),
                ('scan_completed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scan_assets',
            },
        ),
        migrations.CreateModel(
            name='ScanFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scan_findings',
            },
        ),
        migrations.CreateModel(
            name='SecurityHeaderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('present', 'Present'), ('misconfigured', 'Misconfigured')], max_length=20)),
                ('cvss_score', models.FloatField()),
                ('risk_rating', models.CharField(max_length=20)),
                ('recommendation', models.TextField()),
                ('header_value', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_header_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLTLSCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('certificate', 'Certificate'), ('protocol', 'Protocol'), ('cipher', 'Cipher'), ('hsts', 'HSTS')], max_length=50)),
                ('finding', models.TextField()),
                ('example', models.TextField(blank=True)),
                ('cvss_score', models.FloatField()),
                ('risk_rating', models.CharField(max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_expiry', models.DateTimeField(blank=True, null=True)),
                ('certificate_days_remaining', models.IntegerField(blank=True, null=True)),
                ('protocols_supported', models.JSONField(default=list)),
                ('weak_ciphers', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'ssl_tls_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['cve_id'], name='cves_cve_id_cce98d_idx'),
        ),
        migrations.AddIndex(
            model_name='cve',
            index=models.Index(fields=['-cvss_score'], name='cves_cvss_sc_491eaa_idx'),
        ),
        migrations.AddField(
            model_name='dnssecuritycheck',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='api.asset'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status'], name='domains_status_61b3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['expiry_date'], name='domains_expiry__4813a9_idx'),
        ),
        migrations.AddField(
            model_name='asset',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.domain'),
        ),
        migrations.AddField(
            model_name='emailsecuritycheck',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_checks', to='api.asset'),
        ),
        migrations.AddField(
            model_name='finding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.asset'),
        ),
        migrations.AddField(
            model_name='findingcve',
            name='cve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cve_findings', to='api.cve'),
        ),
        migrations.AddField(
            model_name='findingcve',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_cves', to='api.finding'),
        ),
        migrations.AddField(
            model_name='frontendlibrarycheck',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_checks', to='api.asset'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='scans_status_dc5ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['scan_type'], name='scans_scan_ty_d6cfee_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['-created_at'], name='scans_created_7db2e5_idx'),
        ),
        migrations.AddField(
            model_name='frontendlibrarycheck',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_checks', to='api.scan'),
        ),
        migrations.AddField(
            model_name='emailsecuritycheck',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_checks', to='api.scan'),
        ),
        migrations.AddField(
            model_name='dnssecuritycheck',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='api.scan'),
        ),
        migrations.AddField(
            model_name='scanasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_scans', to='api.asset'),
        ),
        migrations.AddField(
            model_name='scanasset',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_assets', to='api.scan'),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_scans', to='api.finding'),
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_findings', to='api.scan'),
        ),
        migrations.AddField(
            model_name='securityheadercheck',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_checks', to='api.asset'),
        ),
        migrations.AddField(
            model_name='securityheadercheck',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_checks', to='api.scan'),
        ),
        migrations.AddField(
            model_name='ssltlscheck',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='api.asset'),
        ),
        migrations.AddField(
            model_name='ssltlscheck',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='api.scan'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['domain', 'asset_type'], name='assets_domain__7e31cc_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['value'], name='assets_value_453ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['asset', 'category'], name='findings_asset_i_f1caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['risk_rating'], name='findings_risk_ra_4c74fc_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status'], name='findings_status_ef7169_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['-cvss_score'], name='findings_cvss_sc_509b9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='findingcve',
            unique_together={('finding', 'cve')},
        ),
        migrations.AlterUniqueTogether(
            name='scanasset',
            unique_together={('scan', 'asset')},
        ),
        migrations.AlterUniqueTogether(
            name='scanfinding',
            unique_together={('scan', 'finding')},
        ),
    ]
