# Generated by Django 6.0.1 on 2026-02-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_frontendlibrarycheck_vulnerability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('category', models.CharField(default='general', max_length=100)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_checks', to='api.scan')),
            ],
        ),
    ]
