# Generated by Django 6.0.1 on 2026-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_technologycheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityheadercheck",
            name="cvss_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
