# Generated by Django 6.0.1 on 2026-06-04 11:14

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scan_cancel_requested_and_cancelled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='domain',
            name='root_domain',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.organisation')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['organisation', 'role', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='dnssecuritycheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_checks', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='domain',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='emailsecuritycheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_checks', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='finding',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='frontendlibrarycheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_checks', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='reportsummary',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_summaries', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='scan',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='securityheadercheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_checks', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='ssltlscheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='api.organisation'),
        ),
        migrations.AddField(
            model_name='technologycheck',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_checks', to='api.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('organisation', 'root_domain')},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('token', models.CharField(default=api.models._default_invite_token, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=api.models._default_invite_expiry)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.organisation')),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invitations_token_5b330c_idx'), models.Index(fields=['email'], name='invitations_email_6e7169_idx')],
            },
        ),
    ]
