# Generated by Django 6.0.1 on 2026-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_organisation_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsummaryfinding',
            name='external_reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reportsummaryfinding',
            name='risk_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
