# Generated by Django 6.0.1 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_platformadmin_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
